link_with 'ASCIIboardContainer', 'ASCIIboard'
pod 'Masonry'
pod 'LIVBubbleMenu', :git => 'https://github.com/Shrugs/LIVBubbleMenu-iOS.git', :branch => 'bganimation-fix'
pod 'ACEDrawingView'
pod 'pop', '~> 1.0'