link_with 'ASCIIboardContainer', 'ASCIIboard'
pod 'Masonry'
pod 'LIVBubbleMenu', :git => 'https://github.com/Shrugs/LIVBubbleMenu-iOS.git', :branch => 'bganimation-fix'
pod 'ACEDrawingView'
pod 'pop', '~> 1.0'
pod 'MCBouncyButton'
pod 'iOS-MagnifyingGlass', '~> 0.0.2'
pod 'JazzHands', '~> 0.1.1'